# Generated by Django 5.2.12 on 2026-03-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='massage',
            new_name='message',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=None, upload_to='students/'),
            preserve_default=False,
        ),
    ]
